---
apiVersion: batch/v1
kind: Job
metadata:
  name: "whippet-12"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "whippet"
    spec:
      containers:
        - name: "whippet"
          image: "asia.gcr.io/nuzihr-286314/whippet:0.2.5"
          env:
            - name: R6STATS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: r6stats
                  key: token
      restartPolicy: Never